[package]
name = "fajt"
version = "0.1.0"
authors = ["Felix Stridsberg <felixstridsberg@gmail.com>"]
edition = "2018"

[workspace]
members = [
    "common",
    "macros",
    "lexer",
    "parser",
]

[dependencies]
clap = "2.33"
fajt_ast = { path = "./ast" }
fajt_parser = { path = "./parser" }
fajt_lexer = { path = "./lexer" }
fajt_common = { path = "./common" }
