[package]
name = "codegen"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fajt_ast = {path = "../ast"}

[dev-dependencies]
fajt_parser = {path = "../parser"}