[package]
name = "fajt_macros"
version = "0.1.0"
authors = ["Felix Stridsberg <felixstridsberg@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = "1.0.69"
quote = "1.0.9"
proc-macro2 = "1.0.26"
